---
- hosts: localhost
  connection: local
  tasks:

     - name: Transfer the text file
       copy: src=name.txt dest=/tmp mode=0777

     - name: Transfer the script
       copy: src=first_name.sh dest=/tmp mode=0777

     - name: Execute the script
       command: sh /tmp/first_name.sh
       register: ps

     # Print the shell task's stdout.
     - debug: msg={{ ps.stdout_lines }}

     - name: Transfer the python script
       copy: src=last_name.py dest=/tmp mode=0777

     - name: Execute the python script
       command: python /tmp/last_name.py
       register: ps2

     # Print the shell task's stdout .
     - debug: msg={{ ps2.stdout_lines }}

